# Generated by Django 4.1.7 on 2023-04-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_profile_profile_info_alter_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_info',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
