# Generated by Django 4.1.7 on 2023-04-01 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_alter_profile_profile_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_info',
            new_name='bio',
        ),
    ]
