# Generated by Django 4.1.7 on 2023-03-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pictures',
            new_name='picture',
        ),
    ]
